<link rel="stylesheet" href="class/css/body_font.css">
<link rel="stylesheet" href="class/css/body_screen.css">
<link rel="stylesheet" href="class/css/font.css">
<link rel="stylesheet" href="class/css/header.css">
<link rel="stylesheet" href="class/css/section.css">
<link rel="stylesheet" href="class/css/footer.css">
<link rel="stylesheet" href="class/css/width.css">
<link rel="stylesheet" href="class/css/flexbox.css">
<link rel="stylesheet" href="class/css/font-size.css">